spring:
  application:
    name: conexa-chalenger-1
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
conexa-chalenger-1-service:
  greeting: "Hello"
  default-value: "World"